import { Rubik } from "next/font/google";
import "./globals.css";
import BlackBtn from "@/components/BlackBtn";
import { IoMdSearch } from "react-icons/io";
import Header from "@/components/Header";
const rubik = Rubik({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  return (
    <html lang="he">
      <body className={rubik.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
